### ISSUE TITLE
exam notifier not showing up under "options"

### ISSUE THREAD

**Issue by elanzora** [AnKing-VIP/exam-notifier#28] opened 2024-07-05 04:48 UTC
exam notifier not showing up under "options"

I have the newest anki version for apple silicon. I also downloaded the newest version of exam notifier. Still would not show up under options 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by abdnh** [comment] 2024-07-13 15:33
This should now be fixed in Anki [24.06.3](https://github.com/ankitects/anki/releases/tag/24.06.3).

**Comment by abdnh** [comment] 2024-07-13 15:37
Reopening as the issue is apparently still there.

**Closed by abdnh** 2024-07-13 15:37 UTC
Labels: bug

**Comment by Kadizta98** [comment] 2024-08-19 17:48
> This should now be fixed in Anki [24.06.3](https://github.com/ankitects/anki/releases/tag/24.06.3).

Is apparently still there for me, please, fix it! :(
